[package]
name = "nbtrs"
version = "0.1.1"
authors = ["Andrew Chin <achin@eminence32.net>"]

[dependencies]
flate2 = "0.2"
byteorder = "0.4"

[[example]]
name = "nbt_dump"
path = "examples/nbt_dump.rs"
